name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          base: "header, activity, repositories"
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: playlist
          plugin_music_playlist: https://open.spotify.com/embed/playlist/7FVbgNOBr18YNiXIEuNwL0
          plugin_music_limit: 4
          token: ${{ secrets.METRICS_TOKEN }}
          # committer_token: ${{ secrets.GITHUB_TOKEN }}
